citewiki/citewiki/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name ="home"),
    path('users/', include('users.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('calendar_of_events/', include('events.urls')),
]

citewiki/teachers/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = "teachers"
urlpatterns = [
    path('', views.index, name="index"),
    path('search/', views.search, name='search'),
    path('add/',views.add, name='add'),
    path('add/process/', views.processadd, name='processadd'),
    path('<int:teacher_id>/details/', views.details, name="details"),
    path('<int:teacher_id>/delete', views.delete_user, name='delete_user'),
    path('<int:teacher_id>/edit', views.edit_user, name='edit_user'),
    path('<int:teacher_id>/process', views.process_edit, name='process_edit'),
    path('addcomment/', views.addcomment, name='addcomment'),
] + static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL,
    document_root = settings.STATIC_ROOT)

citewiki/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register')
]

citewiki/teachers/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.utils.html import mark_safe
import os, random

now = timezone.now()
# Create your models here.

def image_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrst123456890'
    randomstr = ''.join((random.choice(chars)) for x in range(10))
    _now = datetime.now()

    return 'teacher_pic/{year}-{month}-{imageid}-{basename}-{randomstring}{ext}'.\
        format(imageid = instance,
               basename = basefilename,
               randomstring = randomstr,
               ext = file_extension,
               year = _now.strftime('%Y'),
               month = _now.strftime('%m'),
               day = _now.strftime('%d'))


class Subject(models.Model):
    code = models.CharField(max_length=5)
    subject = models.CharField(max_length=32)

    def __str__(self):
        return f"{self.subject}"


class Teacher(models.Model):
    fname = models.CharField(max_length=64, verbose_name="First Name")
    lname = models.CharField(max_length=64, verbose_name="Last Name")
    birthdate = models.DateField(blank=True, null=True)
    email = models.EmailField(unique=True, max_length=64, verbose_name="Email")
    subjects = models.ManyToManyField(Subject, blank=True, related_name="teacher")
    image = models.ImageField(upload_to=image_path, default="teacher_pic/default.jpg")

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />'%(self.image))

    def __str__(self):
        return f"{self.fname} {self.lname}"


class TeacherComment(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField(default='null')
    body = models.TextField(default='null')
    created_on = models.DateTimeField(default=now)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f'Comment {self.body} by {self.name}'

citewiki/teachers/forms.py
from django import forms

from .models import Teacher, Subject

class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = "__all__"

citewiki/teachers/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.paginator import Paginator
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

from .models import Teacher, TeacherComment
from .forms import TeacherForm
# Create your views here.

def index(request):
    teachers = Teacher.objects.all().order_by('fname')

    page_number = request.GET.get('page')
    teachers = Paginator(teachers, 5).get_page(page_number)

    return render(request, 'teachers/index.html', {
        'teachers': teachers
    })

def details(request, teacher_id):
    try:
        teacher = Teacher.objects.get(pk=teacher_id)
        comments = TeacherComment.objects.filter(teacher_id=teacher_id)
        comments_count = TeacherComment.objects.filter(teacher_id=teacher_id).count()

    except Teacher.DoesNotExist:
        raise Http404("Profile does not exist")

    return render(request, 'teachers/details.html', {
        'teachers': teacher,
        'comments': comments,
        'comments_count': comments_count,
    })

def search(request):
    term = request.GET.get('search', '')
    teacher = Teacher.objects.filter(Q(fname__icontains=term) | Q(lname__icontains=term)).order_by('fname')

    paginator = Paginator(teacher, 10)

    page_number = request.GET.get('page')
    teacher = paginator.get_page(page_number)

    return render(request, 'teachers/search.html', {
        'teachers': teacher,
    })

@login_required
def add(request):
    form = TeacherForm(request.POST or None, request.FILES or None)
    return render(request, 'teachers/add.html', {
        'form': form
    })

@login_required
def processadd(request):
    fname = request.POST.get('fname')
    lname = request.POST.get('lname')
    email = request.POST.get('email')
    birthdate = request.POST.get('birthdate')
    form = TeacherForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        subjects = form.cleaned_data.get('subjects')
        form.save()


    if request.FILES.get('image'):
        image = request.FILES.get('image')
        
    else:
        image = 'teacher_pic/default.jpg'

    try:
        n = Teacher.objects.get(email=email)
        # number  already exists
        return HttpResponseRedirect('/teachers')
    
    except ObjectDoesNotExist:
        user = Teacher.objects.create(email=email, fname=fname, lname=lname,
        subjects=subjects, birthdate=birthdate, image=image)

        user.save()
        return HttpResponseRedirect('/teachers')

@login_required
def edit_user(request, teacher_id):
    try:
        teacher = Teacher.objects.get(pk=teacher_id)
        initial = {
            'email':teacher.email,
            'fname': teacher.fname,
            'lname': teacher.lname,
            'subjects': teacher.subjects.all,
            'birthdate': teacher.birthdate,
            'image': teacher.image,
            }
        form = TeacherForm(initial=initial)
        
    except Teacher.DoesNotExist:
        raise Http404("Profile does not exist")

    return render(request, 'teachers/edit.html', {
        'teacher': teacher,
        'form': form
    })

@login_required
def delete_user(request, teacher_id):
    Teacher.objects.filter(pk=teacher_id).delete()
    return HttpResponseRedirect('/teachers')

@login_required
def process_edit(request, teacher_id):
    
    teacher = get_object_or_404(Teacher, pk=teacher_id)
    
    try:
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        birthdate = request.POST.get('birthdate')
        
        if request.FILES.get('image'):
            image = request.FILES.get('image')
        else:
            image = 'teacher_pic/default.jpg'

    except (KeyError, Teacher.DoesNotExist):
        return(request, 'teachers/details.html', {
            'teacher': teacher,
            'form' : form,
            'error_msg': "Problem updating record",
        })
    else:


        teacher_profile = Teacher.objects.get(pk=teacher_id)
        teacher_profile.fname = fname
        teacher_profile.lname = lname
        teacher_profile.email = email
        teacher_profile.birthdate = birthdate

        if image:
            teacher_profile.image = image

        teacher_profile.save()
        return HttpResponseRedirect(reverse('teachers:details', args=(teacher_id,)))

@login_required
def addcomment(request):
    comment_text = request.POST.get('comment')
    teacher_id = request.POST.get('teacher_id')
    name = request.POST.get('name')
    email = request.POST.get('email')

    comment = TeacherComment.objects.create(teacher_id=teacher_id, body=comment_text, name=name, email=email)
    comment.save()
    return HttpResponseRedirect(reverse('teachers:details', args=(teacher_id,)))

citewiki/teachers/templates/teachers/add.html
{% extends 'users/layout.html' %}

{% block title %}Add Teacher{% endblock %}

{% block body %}
{% include 'partials/_navbar.html' %}
<div class="container">
    <h1 class="mt-3 mb-5">Register a Teacher</h1>
    {% if error_msg %}
        <p>{{error_msg}}</p>
    {% endif %}
    <form action="{% url 'teachers:processadd' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <label>First Name:</label>
                <p>{{form.fname}}</p>
        
                <label>Last Name:</label>
                <p>{{form.lname}}</p>
        
                <label>Email:</label>
                <p>{{form.email}}</p>
        
                <label>Subjects:</label>
                <p>{{form.subjects}}</p>

                <a class="btn btn-danger mt-4" href="{% url 'teachers:index' %}" role="button">Back</a>
                <button type="submit" class="btn btn-primary mt-4">Submit</button>
            </div>
            <div class="col">
        
                <label>Birth Date:</label>
                <p><input type="date" name="birthdate" id="id_birthdate" required></p>
        
                <label>Display Image:</label>
                <p>{{form.image}}</p>
            </div>
            
        </div>
    </form>
</div>
{% endblock %}

citewiki/teachers/templates/teachers/details.html
{% extends 'users/layout.html' %}

{% block title %}{{teachers.fname}} {{teachers.lname}}{% endblock %}

{% block body %}
{% include 'partials/_navbar.html' %}
    <div class="container">
        <!-- 1st row -->
        <div class="row">
            <div class="col-sm"></div>
            <div class="col-sm text-center">
                <div class="img-responsive">
                    <img src="/media/{{teachers.image}}" alt="profile user" class="rounded-circle mb-3 mt-3" width="300" height="300">
                </div>
                <div class="btn-group">
                    <a href="{% url 'teachers:delete_user' teachers.id %}" class="btn btn-sm btn-danger">Delete</a>
                    <a href="{% url 'teachers:edit_user' teachers.id %}" class="btn btn-sm btn-info">Edit</a>
                    <a href="{% url 'teachers:index' %}" class="btn btn-sm btn-success">Return</a>
                </div>
                <h1 class="mt-3">{{teachers.fname}} {{teachers.lname}}</h1>
                <p class="text-muted">{{teachers.email}}</p>
            </div>
            <div class="col-sm"></div>
        </div>
        <!-- Bio row -->
        <div class="row mb-5">
            <div class="col-sm-4">
                <div class="m-2 p-2 border border-danger">
                    <h3>Subjects:</h3>
                    <ul>
                        {% for subject in teachers.subjects.all %}
                        <li>{{subject}}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="m-2 p-2 border border-danger">
                    <h3>Birth Date:</h3>
                    <p>{{teachers.birthdate}}</p>
                </div>
            </div>
            <!-- comment section -->
            <div class="col border border-danger p-3">
                <h2>Comments</h2>
            <p class="text-muted">Total of {{comments_count}}</p>
            {% if comments_count > 0 %}
                {% for comment in comments %}
                    {% if comment.active %}
                    <p><strong>{{comment.name}}:</strong> {{comment.body}}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}

            <hr>
            <br>

            <form action="{% url 'teachers:addcomment' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="body">Write you comment</label>
                    <textarea class="form-control" id="comment" name="comment" rows="3"></textarea>
                </div>

                <input type="hidden" name="teacher_id" id="teacher_id" value="{{teachers.id}}">
                <input type="hidden" name="name" id="name" value="{{user.username}}">
                <input type="hidden" name="email" id="email" value="{{user.email}}">

                <button type="submit" class="mt-2 btn btn-sm btn-primary">Add Comment</button>
            </form>
            </div>
        </div>
    </div>
{% endblock %}

citewiki/teachers/templates/teachers/edit.html
{% extends 'users/layout.html' %}

{% block title %}Edit{% endblock %}

{% block body %}
{% include 'partials/_navbar.html' %}
<div class="container">
    <h1 class="mt-3">Edit</h1>
    <p class="text-muted mb-5">User: {{teacher.fname}} {{teacher.lname}}</p>
    {% if error_msg %}
        <p>{{error_msg}}</p>

    {% else %}
        <form action="{% url 'teachers:process_edit' teacher.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="row">
            <div class="col">
                <label>First Name:</label>
                <p>{{form.fname}}</p>
        
                <label>Last Name:</label>
                <p>{{form.lname}}</p>
        
                <label>Email:</label>
                <p>{{form.email}}</p>

                <a class="btn btn-danger mt-4" href="{% url 'teachers:details' teacher.id %}" role="button">Back</a>
                <button type="submit" class="btn btn-primary mt-4">Submit</button>
            </div>
            <div class="col">
        
                <label>Birth Date:</label>
                <p><input type="date" name="birthdate" id="id_birthdate" required></p>
        
                <label>Display Image:</label>
                <p>{{form.image}}</p>
            </div>
            
        </div>
    </form>
    {% endif %}

    
</div>
{% endblock %}

citewiki/teachers/templates/teachers/index.html
{% extends 'users/layout.html' %}

{% block title %}Teachers{% endblock %}

{% block body %}
{% include 'partials/_navbar.html' %}
<div class="container mt-5">
      <form action="{% url 'teachers:search' %}" method='GET' class="mb-4 mt-2">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search name" name="search" required>
          <div class="input-group-append">
            <button type="submit" class="btn btn-success">Search</button>
            <a href="{% url 'teachers:add' %}" class="btn btn-primary" role="button">Add Teacher</a>
          </div>
        </div>
    </form>
    <div class="row">
        <h1>AITES Teachers</h1>
        <div class="col">
            <div class="table-responsive mt-4">
                <table class="table table-bordered table-striped table-hover">
                  <thead>
                    <tr>
                      <th>First Name</th>
                      <th>Last Name</th>
                      <th>Email</th>
                      <th class="text-center">Profile Image</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for teacher in teachers %}
                    <tr>
                        <td>
                          <a class="text-decoration-none" href="{% url 'teachers:details' teacher.id %}">
                            {{teacher.fname}}
                          </a>
                        </td>
                        <td>{{teacher.lname}}</td>
                        <td>{{teacher.email}}</td>
                        <td class="text-center">
                            <a class="text-decoration-none" href="{% url 'teachers:details' teacher.id %}">
                            <img src="/media/{{teacher.image}}" alt="userimage" width="50" class="rounded-circle">
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
                <ul class="pagination">
                    {% if teachers.has_previous %}
                        <li class="page-item"><a href="?page=1" class="page-link">&laquo;  First</a></li>
                        <li class="page-item"><a href="?page={{ teachers.previous_page_number }}" class="page-link"> previous</a></li>
                    {% endif %}

                    {% if teachers.has_next %}
                        <li class="page-item"><a href="?page={{teachers.next_page_number}}" class="page-link">  next</a></li>
                        <li class="page-item"><a href="teachers.paginator.num_pages" class="page-link">&raquo; last</a></li>
                    {% endif %}
                </ul>
              </div>
        </div>
        <div class="col-sm-3">
            <h5 class="mt-4 ms-4 border p-3">Sort by:</h5>
            <ul>
              <li class="ms-4 text-muted">First Name</li>
            </ul>

        </div>

    </div>
</div>
{% endblock %}

citewiki/teachers/templates/teachers/search.html
{% extends 'users/layout.html' %}

{% block title %}Search Results{% endblock %}

{% block body %}
{% include 'partials/_navbar.html' %}

<div class="container mt-2">
    <!-- Searchbar -->
    <form action="{% url 'teachers:search' %}" method='GET' class="mb-4 mt-2">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search name" name="search" required>
          <div class="input-group-append">
            <button type="submit" class="btn btn-success">Search</button>
            <a href="{% url 'teachers:add' %}" class="btn btn-primary" role="button">Add Teacher</a>
          </div>
        </div>
    </form>

    <h1>
        Search Results
    </h1>
    {% if teachers %}
    <div class="row">
        {% if teachers %}
        <div class="table-responsive mt-4">
            <table class="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Email</th>
                  <th class="text-center">Profile Image</th>
                </tr>
              </thead>
              <tbody>
                {% for teacher in teachers %}
                <tr>
                  <td>
                    <a class="text-decoration-none" href="{% url 'teachers:details' teacher.id %}">
                      {{teacher.fname}}
                    </a>
                  </td>
                  <td>{{teacher.lname}}</td>
                  <td>{{teacher.email}}</td>
                  <td class="text-center">
                    <a class="text-decoration-none" href="{% url 'teachers:details' teacher.id %}">
                      <img src="/teachers/media/{{teacher.image}}" alt="userimage" width="50" class="rounded-circle">
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <ul class="pagination">
                {% if teachers.has_previous %}
                    <li class="page-item"><a href="?page=1" class="page-link">&laquo;  First</a></li>
                    <li class="page-item"><a href="?page={{ teachers.previous_page_number }}" class="page-link"> previous</a></li>
                {% endif %}
        
                {% if teachers.has_next %}
                    <li class="page-item"><a href="?page={{teachers.next_page_number}}" class="page-link">  next</a></li>
                    <li class="page-item"><a href="students.paginator.num_pages" class="page-link">&raquo; last</a></li>
                {% endif %}
            </ul>
          </div>
    </div>
    {% else %}
      <h1>
        Search Results
      </h1>
      <p>No query found</p>
    {% endif %}
    {% else %}
    <p>No record.</p>
    {% endif %}
</div>
{% endblock %}