citewiki/citewiki/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name ="home"),
    path('users/', include('users.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('calendar_of_events/', include('events.urls')),
]

citewiki/events/urls.py
from django.urls import path

from . import views

app_name='events'
urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name='add'),
    path('add/process_add', views.process_add, name="process_add")
]

citewiki/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register')
]

citewiki/events/models.py
from django.db import models

# Create your models here.

class Event(models.Model):
    name = models.CharField(max_length=64, verbose_name='name of event')
    info = models.TextField(max_length=128, verbose_name='Information')
    event_date = models.DateField()

    def __str__(self):
        return self.name

citewiki/events/forms.py
from django import forms

from .models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = "__all__"

citewiki/events/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

from .models import Event
from .forms import EventForm
# Create your views here.

def index(request):
    events = Event.objects.all()
    jan = Event.objects.filter(event_date__month="01")
    feb = Event.objects.filter(event_date__month="02")
    mar = Event.objects.filter(event_date__month="03")
    apr = Event.objects.filter(event_date__month="04")
    may = Event.objects.filter(event_date__month="05")
    jun = Event.objects.filter(event_date__month="06")
    jul = Event.objects.filter(event_date__month="07")
    aug = Event.objects.filter(event_date__month="08")
    sept = Event.objects.filter(event_date__month="09")
    octo = Event.objects.filter(event_date__month="10")
    nov = Event.objects.filter(event_date__month="11")
    dec = Event.objects.filter(event_date__month="12")
    return render(request, 'events/index.html', {
        'events': events,
        'jan': jan,
        'feb': feb,
        'mar': mar,
        'apr': apr,
        'may': may,
        'jun': jun,
        'jul': jul,
        'aug': aug,
        'sept': sept,
        'oct': octo,
        'nov': nov,
        'dec': dec
    })

@login_required
def add(request):
    form = EventForm()
    return render(request, 'events/add.html', {
        'form': form
    })

@login_required
def process_add(request):
    name = request.POST.get('name')
    info = request.POST.get('info')
    event_date = request.POST.get('event_date')

    try:
        n = Event.objects.get(name=name)
        # number  already exists
        return render(request, 'events/add.html', {
            'error_msg': "Duplicated event: " + name
        })

    except ObjectDoesNotExist:
        event = Event.objects.create(name=name, info=info, event_date=event_date)

        event.save()
        return HttpResponseRedirect('/calendar_of_events')

citewiki/events/templates/events/add.html
{% extends 'users/layout.html' %}

{% block title %}Add Student{% endblock %}

{% block body %}
{% include 'partials/_navbar.html' %}
<div class="container">
    <h1 class="mt-3 mb-5">Add an event</h1>
    {% if error_msg %}
        <p>{{error_msg}}</p>
    {% endif %}
    <form action="{% url 'events:process_add' %}" method="post">
    {% csrf_token %}
        <div class="row">
            <div class="col">
                <label>Name of event:</label>
                <p>{{form.name}}</p>
                
                <label>Description</label>
                <p>{{form.info}}</p>

                <a class="btn btn-danger mt-4" href="{% url 'events:index' %}" role="button">Back</a>
                <button type="submit" class="btn btn-primary mt-4">Submit</button>
            </div>
            <div class="col">
                <label>Date of Event:</label>
                <p><input type="date" name="event_date" id="id_event_date" required></p>
        </div>
    </form>
</div>
{% endblock %}

citewiki/events/templates/events/index.html
{% extends 'users/layout.html' %}

{% block title %}Calendar of Events{% endblock %}

{% block body %}
{% include 'partials/_navbar.html' %}
    <div class="container">
        <h1 class="mt-4">Calendar of Events <a href="{% url 'events:add' %}" class="btn btn-primary ms-3 mb-2" role="button">Add Event</a></h1>
        {% if jan %}
            <h1>January</h1>
            {% for event in jan %}
                <p><strong>{{event.name}}</strong> - {{event.event_date}}</p>
                <p>Description: {{event.info}}</p>
            {% endfor %}
        {% endif %}
        {% if feb %}
        <h1>February</h1>
        {% for event in feb %}
            <p><strong>{{event.name}}</strong> - {{event.event_date}}</p>
            <p>Description: {{event.info}}</p>
        {% endfor %}
        {% endif %}
        {% if mar %}
        <h1>March</h1>
        {% for event in mar %}
            <p><strong>{{event.name}}</strong> - {{event.event_date}}</p>
            <p>Description: {{event.info}}</p>
        {% endfor %}
        {% endif %}
        {% if apr %}
        <h1>April</h1>
        {% for event in apr %}
            <p><strong>{{event.name}}</strong> - {{event.event_date}}</p>
            <p>Description: {{event.info}}</p>
        {% endfor %}
        {% endif %}
        {% if may %}
        <h1>May</h1>
        {% for event in may %}
            <p><strong>{{event.name}}</strong> - {{event.event_date}}</p>
            <p>Description: {{event.info}}</p>
        {% endfor %}
        {% endif %}
        {% if jun %}
        <h1>June</h1>
        {% for event in jun %}
            <p><strong>{{event.name}}</strong> - {{event.event_date}}</p>
            <p>Description: {{event.info}}</p>
        {% endfor %}
        {% endif %}
        {% if jul %}
        <h1>July</h1>
        {% for event in jul %}
            <p><strong>{{event.name}}</strong> - {{event.event_date}}</p>
            <p>Description: {{event.info}}</p>
        {% endfor %}
        {% endif %}
        {% if aug %}
        <h1>August</h1>
        {% for event in aug %}
            <p><strong>{{event.name}}</strong> - {{event.event_date}}</p>
            <p>Description: {{event.info}}</p>
        {% endfor %}
        {% endif %}
        {% if sept %}
        <h1>September</h1>
        {% for event in sept %}
            <p><strong>{{event.name}}</strong> - {{event.event_date}}</p>
            <p>Description: {{event.info}}</p>
        {% endfor %}
        {% endif %}
        {% if oct %}
        <h1>October</h1>
        {% for event in oct %}
            <p><strong>{{event.name}}</strong> - {{event.event_date}}</p>
            <p>Description: {{event.info}}</p>
        {% endfor %}
        {% endif %}
        {% if nov %}
        <h1>November</h1>
        {% for event in nov %}
            <p><strong>{{event.name}}</strong> - {{event.event_date}}</p>
            <p>Description: {{event.info}}</p>
        {% endfor %}
        {% endif %}
        {% if mar %}
        <h1>December</h1>
        {% for event in dec %}
            <p><strong>{{event.name}}</strong> - {{event.event_date}}</p>
            <p>Description: {{event.info}}</p>
        {% endfor %}
        {% endif %}
    </div>
{% endblock %}