citewiki/citewiki/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name ="home"),
    path('users/', include('users.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('calendar_of_events/', include('events.urls')),
]

citewiki/events/urls.py
from django.urls import path

from . import views

app_name='events'
urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name='add'),
    path('add/process_add', views.process_add, name="process_add")
]

citewiki/students/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'students'
urlpatterns = [
    path('',views.index, name='index'),
    path('search/', views.search, name='search'),
    path('add/',views.add, name='add'),
    path('add/process/', views.processadd, name='process_add'),
    path('<int:profile_id>/details', views.details, name='details'),
    path('<int:profile_id>/delete', views.delete_user, name='delete_user'),
    path('<int:profile_id>/edit', views.edit_user, name='edit_user'),
    path('<int:profile_id>/process', views.process_edit, name='process_edit'),
    path('addcomment/', views.addcomment, name='addcomment'),
] + static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL,
    document_root = settings.STATIC_ROOT)

citewiki/teachers/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = "teachers"
urlpatterns = [
    path('', views.index, name="index"),
    path('search/', views.search, name='search'),
    path('add/',views.add, name='add'),
    path('add/process/', views.processadd, name='processadd'),
    path('<int:teacher_id>/details/', views.details, name="details"),
    path('<int:teacher_id>/delete', views.delete_user, name='delete_user'),
    path('<int:teacher_id>/edit', views.edit_user, name='edit_user'),
    path('<int:teacher_id>/process', views.process_edit, name='process_edit'),
    path('addcomment/', views.addcomment, name='addcomment'),
] + static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL,
    document_root = settings.STATIC_ROOT)

citewiki/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register')
]

citewiki/users/models.py
from django.db import models

# Create your models here.

citewiki/users/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model

User = get_user_model()

class UserRegistrationForm(forms.ModelForm):
    email = forms.EmailField(label='email address')
    email2 = forms.EmailField(label='confirm email address')
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'email2',
            'password',
        ]
    
    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')

        if email != email2:
            raise forms.ValidationError('Email not match')
        
        email_qs = User.objects.filter(email=email)

        if email_qs.exists():
            raise forms.ValidationError(
                'This email is already used'
            )
        
        return super(UserRegistrationForm, self).clean(*args, **kwargs)

citewiki/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate, get_user_model

from students.models import StudentComment
from teachers.models import TeacherComment
from .forms import UserRegistrationForm
# Create your views here.
def index(request):
    students = StudentComment.objects.all()
    return render(request, 'users/index.html', {
        'students' : students,
    })

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user)
            return HttpResponseRedirect(reverse('users:index'))
        else:
            return render(request, 'users/login.html', {
                'msg': "Invalid credentials"
            })

    return render(request, 'users/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'users/login.html', {
        'msg': "Logged out"
    })


def register_view(request):
    next = request.GET.get('next')
    form = UserRegistrationForm(request.POST or None)

    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)

        if next:
            return redirect(next)
        
        return redirect('/')

    context = {
        'form' : form
    }

    return render(request, 'users/signup.html', context)

def logout_view(request):
    logout(request)
    return redirect('/')

citewiki/users/templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom border border-danger">
    <div class="container-fluid ">
      <a class="navbar-brand text-danger" href="{% url 'users:index' %}"> <img class="ms-4 me-3" src="{% static 'logo/citelogo.png' %}" alt="citelogo" width="40">JMC AITES Wiki</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              AITES
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'students:index' %}">Students</a></li>
              <li><a class="dropdown-item" href="{% url 'teachers:index' %}">Teachers</a></li>
            </ul>
          </li>
          <li class="nav-item m-auto">
            <a href="{% url 'events:index' %}" class="nav-link text-dark" >Calendar of Events</a>
          </li>
        </ul>
        <div class="d-flex ms-auto pe-3">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <span class="navbar-text text-dark">Welcome, {{request.user.username}} | </span>
                    <li class='nav-item'>
                        <a href="{% url 'users:logout' %}" class="nav-link text-primary">logout</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'users:register' %}" class="nav-link text-primary">Register</a>
                    </li>
                    <li>
                      <a href="{% url 'users:login' %}" class="nav-link text-primary">Login</a>
                  </li>
                {% endif %}

            </ul>
        </div>
      </div>
    </div>
</nav>