citewiki/citewiki/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name ="home"),
    path('users/', include('users.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('calendar_of_events/', include('events.urls')),
]

citewiki/students/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'students'
urlpatterns = [
    path('',views.index, name='index'),
    path('search/', views.search, name='search'),
    path('add/',views.add, name='add'),
    path('add/process/', views.processadd, name='process_add'),
    path('<int:profile_id>/details', views.details, name='details'),
    path('<int:profile_id>/delete', views.delete_user, name='delete_user'),
    path('<int:profile_id>/edit', views.edit_user, name='edit_user'),
    path('<int:profile_id>/process', views.process_edit, name='process_edit'),
    path('addcomment/', views.addcomment, name='addcomment'),
] + static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL,
    document_root = settings.STATIC_ROOT)

citewiki/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register')
]

citewiki/students/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.utils.html import mark_safe
import os, random

now = timezone.now()
# Create your models here.
def image_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrst123456890'
    randomstr = ''.join((random.choice(chars)) for x in range(10))
    _now = datetime.now()

    return 'profile_pic/{year}-{month}-{imageid}-{basename}-{randomstring}{ext}'.\
        format(imageid = instance,
               basename = basefilename,
               randomstring = randomstr,
               ext = file_extension,
               year = _now.strftime('%Y'),
               month = _now.strftime('%m'),
               day = _now.strftime('%d'))

class Program(models.Model):
    code = models.CharField(max_length=5, verbose_name="code")
    program = models.CharField(max_length=64, verbose_name="program")

    def __str__(self):
        return f"{self.program}"

class Student(models.Model):
    YEAR_LEVEL = [
        ('I','First Year'),
        ('II','Second Year'),
        ('III','Third Year'),
        ('IV','Fourth Year')
    ]

    fname = models.CharField(max_length=64, verbose_name='first name')
    lname = models.CharField(max_length=64, verbose_name='last name')
    birth_date = models.DateField(blank=True, null=True)
    student_program = models.ForeignKey(Program, on_delete = models.CASCADE, related_name="student_program", verbose_name='program')
    email = models.EmailField(unique=True, max_length=64, verbose_name='email')
    yearlevel = models.CharField(max_length=5, choices=YEAR_LEVEL, verbose_name='year level')
    user_image = models.ImageField(upload_to=image_path, default='profile_pic/default.jpg')

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" />'%(self.user_image))


    def __str__(self):
        return f"{self.email}"

class StudentComment(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField(default='null')
    body = models.TextField(default='null')
    created_on = models.DateTimeField(default=now)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f'Comment {self.body} by {self.name}'

citewiki/students/forms.py
from django import forms

from .models import Student, StudentComment

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

class CommentForm(forms.ModelForm):
    class Meta:
        model = StudentComment
        fields = "__all__"

citewiki/students/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponseRedirect,Http404
from django.core.paginator import Paginator
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required

from .models import Student, Program, StudentComment
from .forms import StudentForm

# Create your views here.
def index(request):
    students = Student.objects.filter(yearlevel='I').order_by('fname')
    studentsii = Student.objects.filter(yearlevel='II').order_by('fname')
    studentsiii = Student.objects.filter(yearlevel='III').order_by('fname')
    studentsiv = Student.objects.filter(yearlevel='IV').order_by('fname')
    

    page_number = request.GET.get('page')
    students = Paginator(students, 5).get_page(page_number)
    page_numberii = request.GET.get('pageii')
    studentsii = Paginator(studentsii, 5).get_page(page_numberii)
    page_numberiii = request.GET.get('pageiii')
    studentsiii = Paginator(studentsiii, 5).get_page(page_numberiii)

    context = {
        'students': students,
        'studentsii': studentsii,
        'studentsiii': studentsiii,
        'studentsiv': studentsiv,
    }
    return render(request, 'students/index.html', context)

def details(request,profile_id):
        try:
            user = Student.objects.get(pk=profile_id)
            comments = StudentComment.objects.filter(student_id=profile_id)
            comments_count = StudentComment.objects.filter(student_id=profile_id).count()
        except Student.DoesNotExist:
            raise Http404("Profile does not exist")

        return render(request,'students/detail.html',{
                'user_details': user,
                'comments': comments,
                'comments_count': comments_count,
            })

def search(request):
    term = request.GET.get('search', '')
    student = Student.objects.filter(Q(fname__icontains=term) | Q(lname__icontains=term)).order_by('fname')

    paginator = Paginator(student, 10)

    page_number = request.GET.get('page')
    student = paginator.get_page(page_number)

    return render(request, 'students/search.html', {
        'students': student,
    })

@login_required
def add(request):
    form = StudentForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
  
    return render(request, 'students/add.html', {
        'form': form
    })

@login_required
def processadd(request):
    fname = request.POST.get('fname')
    lname = request.POST.get('lname')
    email = request.POST.get('email')
    program = Program.objects.get(pk=request.POST.get('student_program'))
    yearlevel = request.POST.get('yearlevel')
    birth_date = request.POST.get('birth_date')

    if request.FILES.get('user_image'):
        user_image = request.FILES.get('user_image')
    else:
        user_image = 'profile_pic/default.jpg'

    try:
        n = Student.objects.get(email=email)
        # number  already exists
        return render(request, 'students/add.html', {
            'error_msg': "Duplicated email: " + email
        })

    except ObjectDoesNotExist:
        user = Student.objects.create(email=email, fname=fname, lname=lname,
        student_program=program, yearlevel=yearlevel, birth_date=birth_date,
        user_image=user_image)

        user.save()
        return HttpResponseRedirect('/students')

@login_required
def delete_user(request, profile_id):
    Student.objects.filter(pk=profile_id).delete()
    return HttpResponseRedirect('/students')

@login_required
def edit_user(request, profile_id):
    try:
        user = Student.objects.get(pk=profile_id)
        initial = {
            'email':user.email,
            'fname': user.fname,
            'lname': user.lname,
            'student_program': user.student_program,
            'yearlevel': user.yearlevel,
            'birth_date': user.birth_date,
            'user_image': user.user_image,
            }
        form = StudentForm(request.POST or None, request.FILES or None,initial=initial)
        if form.is_valid():
            form.save()
    except Student.DoesNotExist:
        raise Http404("Profile does not exist")
    return render(request, 'students/edit.html', {
        'student_user': user,
        'form': form
    })

@login_required
def process_edit(request, profile_id):
    
    user = get_object_or_404(Student, pk=profile_id)
    try:
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        program = Program.objects.get(pk=request.POST.get('student_program'))
        yearlevel = request.POST.get('yearlevel')
        birth_date = request.POST.get('birth_date')
        
        if request.FILES.get('user_image'):
            user_image = request.FILES.get('user_image')
        else:
            user_image = 'profile_pic/default.jpg'
    except (KeyError, Student.DoesNotExist):
        return(request, 'students/detail.html', {
            'user': user,
            'error_msg': "Problem updating record",
        })
    else:
        user_profile = Student.objects.get(id=profile_id)
        user_profile.fname = fname
        user_profile.lname = lname
        user_profile.email = email
        user_profile.student_program = program
        user_profile.yearlevel = yearlevel
        user_profile.birth_date = birth_date

        if user_image:
            user_profile.user_image = user_image
        user_profile.save()
        return HttpResponseRedirect(reverse('students:details', args=(profile_id,)))
    
@login_required
def addcomment(request):
    comment_text = request.POST.get('comment')
    student_id = request.POST.get('student_id')
    name = request.POST.get('name')
    email = request.POST.get('email')

    comment = StudentComment.objects.create(student_id=student_id, body=comment_text, name=name, email=email)
    comment.save()
    return HttpResponseRedirect(reverse('students:details', args=(student_id,)))

citewiki/students/templates/students/add.html
{% extends 'users/layout.html' %}

{% block title %}Add Student{% endblock %}

{% block body %}
{% include 'partials/_navbar.html' %}
<div class="container">
    <h1 class="mt-3 mb-5">Register a Student</h1>
    {% if error_msg %}
        <p>{{error_msg}}</p>
    {% endif %}
    <form action="{% url 'students:process_add' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="row">
            <div class="col">
                <label>First Name:</label>
                <p>{{form.fname}}</p>
        
                <label>Last Name:</label>
                <p>{{form.lname}}</p>
        
                <label>Email:</label>
                <p>{{form.email}}</p>
        
                <label>Program:</label>
                <p>{{form.student_program}}</p>

                <a class="btn btn-danger mt-4" href="{% url 'students:index' %}" role="button">Back</a>
                <button type="submit" class="btn btn-primary mt-4">Submit</button>
            </div>
            <div class="col">
                <label>Year Level:</label>
                <p>{{form.yearlevel}}</p>
        
                <label>Birth Date:</label>
                <p><input type="date" name="birth_date" id="id_birth_date" required></p>
        
                <label>Display Image:</label>
                <p>{{form.user_image}}</p>
            </div>
            
        </div>
    </form>
</div>
{% endblock %}

citewiki/students/templates/students/detail.html
{% extends 'users/layout.html' %}

{% block title %}{{user_details.fname}} {{user_details.lname}}{% endblock %}

{% block body %}
{% include 'partials/_navbar.html' %}
    <div class="container">
        <!-- 1st row -->
        <div class="row">
            <div class="col-sm"></div>
            <div class="col-sm text-center">
                <div class="img-responsive">
                    <img src="/media/{{user_details.user_image}}" alt="profile user" class="rounded-circle mb-3 mt-4" width="300" height="300">
                </div>
                <div class="btn-group">
                    <a href="{% url 'students:delete_user' user_details.id %}" class="btn btn-sm btn-danger">Delete</a>
                    <a href="{% url 'students:edit_user' user_details.id %}" class="btn btn-sm btn-info">Edit</a>
                    <a href="{% url 'students:index' %}" class="btn btn-sm btn-success">Return</a>
                </div>
                <h1 class="mt-3">{{user_details.fname}} {{user_details.lname}}</h1>
                <p class="text-muted">Year Level: {{user_details.yearlevel}}</p>
            </div>
            <div class="col-sm"></div>
        </div>
        <!-- Bio row -->
        <div class="row mb-5">
            <div class="col-sm-4">
                <div class="m-2 p-2 border border-danger">
                    <h3>Program:</h3>
                    <p>{{user_details.student_program.program}}</p>
                </div>
                <div class="m-2 p-2 border border-danger">
                    <h3>Birth Date:</h3>
                    <p>{{user_details.birth_date}}</p>
                </div>
                <div class="m-2 p-2 border border-danger">
                    <h3>Email:</h3>
                    <p>{{user_details.email}}</p>
                </div>
            </div>
            <!-- comment section -->
            <div class="col border border-danger p-3">
                <h2>Comments</h2>
            <p class="text-muted">Total of {{comments_count}}</p>
            {% if comments_count > 0 %}
                {% for comment in comments %}
                    {% if comment.active %}
                    <p><strong>{{comment.name}}:</strong> {{comment.body}}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}

            <hr>
            <br>

            <form action="{% url 'students:addcomment' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="body">Write you comment</label>
                    <textarea class="form-control" id="comment" name="comment" rows="3"></textarea>
                </div>

                <input type="hidden" name="student_id" id="student_id" value="{{user_details.id}}">
                <input type="hidden" name="name" id="name" value="{{user.username}}">
                <input type="hidden" name="email" id="email" value="{{user.email}}">

                <button type="submit" class="mt-2 btn btn-sm btn-primary">Add Comment</button>
            </form>
            </div>
        </div>
    </div>
{% endblock %}

citewiki/students/templates/students/edit.html
{% extends 'users/layout.html' %}

{% block title %}Edit{% endblock %}

{% block body %}
{% include 'partials/_navbar.html' %}
<div class="container">
    <h1 class="mt-3">Edit</h1>
    <p class="text-muted mb-5">User: {{student_user.fname}} {{student_user.lname}}</p>
    {% if error_msg %}
        <p>{{error_msg}}</p>
    {% endif %}

    <form action="{% url 'students:process_edit' student_user.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="row">
            <div class="col">
                <label>First Name:</label>
                <p>{{form.fname}}</p>
        
                <label>Last Name:</label>
                <p>{{form.lname}}</p>
        
                <label>Email:</label>
                <p>{{form.email}}</p>
        
                <label>Program:</label>
                <p>{{form.student_program}}</p>

                <a class="btn btn-danger mt-4" href="{% url 'students:details' student_user.id %}" role="button">Back</a>
                <button type="submit" class="btn btn-primary mt-4">Submit</button>
            </div>
            <div class="col">
                <label>Year Level:</label>
                <p>{{form.yearlevel}}</p>
        
                <label>Birth Date:</label>
                <p><input type="date" name="birth_date" id="id_birth_date" required></p>
        
                <label>Display Image:</label>
                <p>{{form.user_image}}</p>
            </div>
            
        </div>
    </form>
</div>
{% endblock %}

citewiki/students/templates/students/index.html
{% extends 'users/layout.html' %}

{% block title %}Students{% endblock %}

{% block body %}
{% include 'partials/_navbar.html' %}

<div class="container mt-5">
    <!-- Searchbar -->
    <form action="{% url 'students:search' %}" method='GET' class="mb-4 mt-2">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search name" name="search" required>
          <div class="input-group-append">
            <button type="submit" class="btn btn-success">Search</button>
            <a href="{% url 'students:add' %}" class="btn btn-primary" role="button">Add Student</a>
          </div>
        </div>
    </form>
    <!-- 1st year students -->
    <div class="row">
        <h1>
          AITES 1st year Students
        </h1>
        {% if students %}
        <div class="table-responsive mt-4">
            <table class="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Program</th>
                  <th>Email</th>
                  <th class="text-center">Profile Image</th>
                </tr>
              </thead>
              <tbody>
                {% for student in students %}
                <tr>
                    <td>
                      <a class="text-decoration-none" href="{% url 'students:details' student.id %}">
                        {{student.fname}}
                      </a>
                    </td>
                    <td>{{student.lname}}</td>
                    <td>{{student.student_program.program}}</td>
                    <td>{{student.email}}</td>
                    <td class="text-center">
                        <a class="text-decoration-none" href="{% url 'students:details' student.id %}">
                        <img src="/media/{{student.user_image}}" alt="userimage" width="50" class="rounded-circle">
                        </a>
                    </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <ul class="pagination">
                {% if students.has_previous %}
                    <li class="page-item"><a href="?page=1" class="page-link">&laquo;  First</a></li>
                    <li class="page-item"><a href="?page={{ students.previous_page_number }}" class="page-link"> previous</a></li>
                {% endif %}

                {% if students.has_next %}
                    <li class="page-item"><a href="?page={{students.next_page_number}}" class="page-link">  next</a></li>
                    <li class="page-item"><a href="students.paginator.num_pages" class="page-link">&raquo; last</a></li>
                {% endif %}
            </ul>
          </div>
    </div>
    {% else %}
    <p>No record.</p>
    {% endif %}
    <!-- 2nd Year Students -->
    <div class="row">
        <h1>AITES 2nd Year Students</h1>
        {% if studentsii %}
        <div class="table-responsive mt-4">
            <table class="table table-bordered table-striped table-hover">
              <thead>
                <tr>

                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Program</th>
                  <th>Email</th>
                  <th class="text-center">Profile Image</th>
                </tr>
              </thead>
              <tbody>
                {% for student in studentsii %}
                <tr>
                  <td>
                    <a class="text-decoration-none" href="{% url 'students:details' student.id %}">
                      {{student.fname}}
                    </a>
                  </td>
                  <td>{{student.lname}}</td>
                  <td>{{student.student_program.program}}</td>
                  <td>{{student.email}}</td>
                  <td class="text-center">
                    <a class="text-decoration-none" href="{% url 'students:details' student.id %}">
                      <img src="/media/{{student.user_image}}" alt="userimage" width="50" class="rounded-circle">
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <ul class="pagination">
                {% if studentsii.has_previous %}
                    <li class="page-item"><a href="?pageii=1" class="page-link">&laquo;  First</a></li>
                    <li class="page-item"><a href="?pageii={{ studentsii.previous_page_number }}" class="page-link"> previous</a></li>
                {% endif %}

                {% if studentsii.has_next %}
                    <li class="page-item"><a href="?pageii={{studentsii.next_page_number}}" class="page-link">  next</a></li>
                    <li class="page-item"><a href="studentsii.paginator.num_pages" class="page-link">&raquo; last</a></li>
                {% endif %}
            </ul>
          </div>
    </div>
    {% else %}
    <p>No record.</p>
    {% endif %}
    <!-- 3rd Year Students -->
    <div class="row">
        <h1>AITES 3rd Year Students</h1>
        {% if studentsiii %}
        <div class="table-responsive mt-4">
            <table class="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Program</th>
                  <th>Email</th>
                  <th class="text-center">Profile Image</th>
                </tr>
              </thead>
              <tbody>
                {% for student in studentsiii %}
                <tr>
                  <td>
                    <a class="text-decoration-none" href="{% url 'students:details' student.id %}">
                      {{student.fname}}</td>
                    </a>
                  <td>{{student.lname}}</td>
                  <td>{{student.student_program.program}}</td>
                  <td>{{student.email}}</td>
                  <td class="text-center">
                    <a class="text-decoration-none" href="{% url 'students:details' student.id %}">
                      <img src="/media/{{student.user_image}}" alt="userimage" width="50" class="rounded-circle">
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <ul class="pagination">
                {% if studentsiii.has_previous %}
                    <li class="page-item"><a href="?pageiii=1" class="page-link">&laquo;  First</a></li>
                    <li class="page-item"><a href="?pageiii={{ studentsiii.previous_page_number }}" class="page-link"> previous</a></li>
                {% endif %}

                {% if studentsiii.has_next %}
                    <li class="page-item"><a href="?pageiii={{studentsiii.next_page_number}}" class="page-link">  next</a></li>
                    <li class="page-item"><a href="studentsiii.paginator.num_pages" class="page-link">&raquo; last</a></li>
                {% endif %}
            </ul>
          </div>
          {% else %}
          <p>No record.</p>
          {% endif %}
      </div>
      <!-- 4th Year Students -->
      <div class="row">
        <h1>AITES 4th Year Students</h1>
        {% if studentsiv %}
        <div class="table-responsive mt-4">
            <table class="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Program</th>
                  <th>Email</th>
                  <th class="text-center">Profile Image</th>
                </tr>
              </thead>
              <tbody>
                {% for student in studentsiv %}
                <tr>
                  <td>
                    <a class="text-decoration-none" href="{% url 'students:details' student.id %}">
                      {{student.fname}}</td>
                    </a>
                  <td>{{student.lname}}</td>
                  <td>{{student.student_program.program}}</td>
                  <td>{{student.email}}</td>
                  <td class="text-center">
                    <a class="text-decoration-none" href="{% url 'students:details' student.id %}">
                      <img src="/media/{{student.user_image}}" alt="userimage" width="50" class="rounded-circle">
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <ul class="pagination">
                {% if studentsiv.has_previous %}
                    <li class="page-item"><a href="?pageiv=1" class="page-link">&laquo;  First</a></li>
                    <li class="page-item"><a href="?pageiv={{ studentsiv.previous_page_number }}" class="page-link"> previous</a></li>
                {% endif %}

                {% if studentsiv.has_next %}
                    <li class="page-item"><a href="?pageiv={{studentsiv.next_page_number}}" class="page-link">  next</a></li>
                    <li class="page-item"><a href="studentsiv.paginator.num_pages" class="page-link">&raquo; last</a></li>
                {% endif %}
            </ul>
          </div>
          {% else %}
          <p>No record.</p>
          {% endif %}
      </div>
</div>
{% endblock %}

citewiki/students/templates/students/search.html
{% extends 'users/layout.html' %}

{% block title %}Search Results{% endblock %}

{% block body %}
{% include 'partials/_navbar.html' %}

<div class="container mt-2">
    <!-- Searchbar -->
    <form action="{% url 'students:search' %}" method='GET' class="mb-4 mt-2">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search name" name="search" required>
          <div class="input-group-append">
            <button type="submit" class="btn btn-success">Search</button>
            <a href="{% url 'students:add' %}" class="btn btn-primary" role="button">Add Student</a>
          </div>
        </div>
    </form>

    <h1>
        Search Results
    </h1>
    {% if students %}
    <div class="row">
        {% if students %}
        <div class="table-responsive mt-4">
            <table class="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>yearlevel</th>
                  <th>Program</th>
                  <th>Email</th>
                  <th class="text-center">Profile Image</th>
                </tr>
              </thead>
              <tbody>
                {% for student in students %}
                <tr>
                  <td>
                    <a class="text-decoration-none" href="{% url 'students:details' student.id %}">
                      {{student.fname}}
                    </a>
                  </td>
                  <td>{{student.lname}}</td>
                  <td>{{student.yearlevel}}</td>
                  <td>{{student.student_program.program}}</td>
                  <td>{{student.email}}</td>
                  <td class="text-center">
                    <a class="text-decoration-none" href="{% url 'students:details' student.id %}">
                      <img src="/students/media/{{student.user_image}}" alt="userimage" width="50" class="rounded-circle">
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <ul class="pagination">
                {% if students.has_previous %}
                    <li class="page-item"><a href="?page=1" class="page-link">&laquo;  First</a></li>
                    <li class="page-item"><a href="?page={{ students.previous_page_number }}" class="page-link"> previous</a></li>
                {% endif %}
        
                {% if students.has_next %}
                    <li class="page-item"><a href="?page={{students.next_page_number}}" class="page-link">  next</a></li>
                    <li class="page-item"><a href="students.paginator.num_pages" class="page-link">&raquo; last</a></li>
                {% endif %}
            </ul>
          </div>
    </div>
    {% else %}
      <h1>
        Search Results
      </h1>
      <p>No query found</p>
    {% endif %}
    {% else %}
    <p>No record.</p>
    {% endif %}
</div>
{% endblock %}